language: php

php:
  - 5.6

install:
  - composer require satooshi/php-coveralls

before_script:
  - mkdir -p build/logs
  - composer install

script:
  - bin/phpunit -c app/phpunit.xml.dist

after_success:
  - bin/coveralls -v