services:
    dg_openticket.table_prefix_subscriber:
        class: DG\OpenticketBundle\EventSubscriber\TablePrefixEventSubscriber
        arguments: [null]
        tags:
            - {name: doctrine.event_subscriber}
