imports:
    - {resource: 'services/fixtures.yml'}
    - {resource: 'services/commands.yml'}
    - {resource: 'services/repositories.yml'}
    - {resource: 'services/translation.yml'}

services:
    dg_openticket.table_prefix_subscriber:
        class: DG\OpenticketBundle\EventSubscriber\TablePrefixEventSubscriber
        arguments: [null] # will be replaced in DGOpenticketExtension
        tags:
            - {name: doctrine.event_subscriber}
